---
#
# Let's try to create a per-tenant default Namespace
# to solve the chicken&egg problem, due to the fact
# that the Tenant's GitOps reconciler should reconcile
# resources in his Tenant Namespaces, but it should be able also
# to create its Tenant's Namespaces.
#
# So we put the Tenant GitOps reconciler in a per-Tenant
# default Namespace which is created by the "parent" Flux GitOps
# reconciler:
#
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
    capsule.clastix.io/tenant: dev-team
  name: dev-team

#---
# Then, other Tenant Namespaces will be instantiated by the Tenant user
# themselves. I.e. the GitOps way, by the Tenat Owner gitops-reconciler
# Service Account, not by the platform admin here.
#
# Instead, the Tenant admin will declare it in the Tenant Sync (GitRepo+
# Kustomization).
#
#apiVersion: v1
#kind: Namespace
#metadata:
#  labels:
#    toolkit.fluxcd.io/tenant: dev-team
#  name: apps
#
---
#
# A Tenant as a set of Namespaces, is owned by the Service Account
# gitops-reconciler, instead of dev-team.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-reconciler
  namespace: dev-team

---
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: dev-team
spec:
  owners:
  - name: system:serviceaccount:dev-team:gitops-reconciler
    kind: ServiceAccount

---
#
# The service account gitops-reconciler (in dev-team Namespace)
# has to be part of Capsule group, pass through Capsule access control.
#
apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  name: default
spec:
  userGroups:
  - system:serviceaccounts:dev-team

#---
#
# This is no longer needed. Instead Tenant.spec.owners is what matters.
#
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  labels:
#    toolkit.fluxcd.io/tenant: dev-team
#  name: dev-team
#  namespace: apps
#
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  labels:
#    toolkit.fluxcd.io/tenant: dev-team
#  name: gotk-reconciler
#  namespace: apps
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: cluster-admin
#subjects:
#- kind: User
#  name: gotk:apps:reconciler
#- kind: ServiceAccount
#  name: dev-team
#  namespace: apps
