apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-team
  namespace: apps
spec:
  interval: 1m
  url: ssh://git@github.com/maxgio92/flux2-multi-tenancy
  ref:
    branch: dev-team
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  serviceAccountName: dev-team
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-team
  prune: true
  validation: client


