apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-team
  namespace: default
spec:
  interval: 1m
  url: ssh://git@github.com/maxgio92/flux2-multi-tenancy
  ref:
    branch: dev-team-with-capsule
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: default
spec:
  serviceAccountName: dev-team-gitops-reconciler
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-team
  prune: true
  validation: client


