apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-team
  namespace: default
spec:
  interval: 1m
  url: https://github.com/maxgio92/flux2-capsule-multi-tenancy.git
  ref:
    branch: dev-team-with-capsule
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: default
spec:
  serviceAccountName: dev-team-gitops-reconciler
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-team
  prune: true
  validation: client


